### ISSUE TITLE
Can't create files/directories in root directory

### ISSUE THREAD

**Issue by gerow** [klange/toaruos#100]
Recreation steps:
- Login as root

# touch /a
# cat /a
cat: /a: no such file or directory

ls shows an entry called "/a", but that's it.

I went back to 478835401ecf44391a3b32cfa178b1d56bde1c11 to check and see if this is a regression caused by the symlink stuff, but it appears to have existed since before then.

**Comment by gerow** [comment]
markdown, plz, just let me type

**Comment by klange** [comment]
This is probably why we end up with random `/tmp` directories in our root... I suspect a weird edge case in the path parsing when we're at the root.
