### ISSUE TITLE
Checking Privileges?

### ISSUE THREAD

**Issue by geyslan** [klange/toaruos#104]
![screenshot_2015_07_12_21_39_43](https://cloud.githubusercontent.com/assets/3372117/8640902/982dc734-28de-11e5-8d0f-c859fa45170a.png)

**Comment by geyslan** [comment]
I think I got it: [ Security Issues - Tracking Ticket #95 ](https://github.com/klange/toaruos/issues/95)

**Comment by klange** [comment]
Closing as duplicate, lack of filesystem permissions is pretty well known.

**Comment by klange** [comment]
Nice approach of rewriting sudo with its setuid bit set to do your bidding, though of course sudo itself would have gladly given you root either way...
