### ISSUE TITLE
Feature Request: Packaging system

### ISSUE THREAD

**Issue by gerow** [klange/toaruos#105]
Figure an issue should probably be open for this. The plan is to implement some kind of packaging system for toaruos. The details of how it will work are still not complete, but I'm fairly certain we'll need to be able to read/write some archive format in order to make it easier to bundle files together, tar is the obvious first choice.

I'm currently trying to port libarchive (http://www.libarchive.org/) to toaruos and it's going _okay_ I guess.

**Comment by makerimages** [comment]
Problably dependent on the Userspace interface of #44.

**Comment by gerow** [comment]
While having repositories over a network link would be nice (and an ultimate goal) I don't think it's really a strict dependency. I'm thinking in its first iteration the only kind of repository it will support will be from a filesystem. That could just be somewhere like /usr/share/repo or it could be on a CD that is mounted in a similar location.

**Comment by klange** [comment]
I'm going to link into merging the libarchive branch.

We can actually download packages or binaries with the current web stack, though it still needs a lot of work:

![downloaded pdfviewer](http://i.imgur.com/uD25Dh0.png)

**Comment by PoisonNinja** [comment]
This issue was moved to PoisonNinja/ToyOS#2

**Comment by randohinn** [comment]
I think `get-py` now pretty much covers this, right?

**Comment by klange** [comment]
`get-py` is a temporary implementation. I think I'll leave this issue open until we have something more complete, which I plan on working on this week.
