### ISSUE TITLE
RTL8169 network drivers

### ISSUE THREAD

**Issue by klange** [klange/toaruos#108]
We have an RTL8139 driver. The RTL8169 is fairly similar and should be able to work off of the existing codebase, but is not sufficiently compatible that we can use the existing driver. Supporting the RTL8169 will get us network support on some physical hardware (both of my test rigs use this chipset, and one of them actually has two NICs).

**Comment by hlechner** [comment]
**RTL8187** is an interesting option too.

The popular Alfa AWUS036H (it's USB) commonly used on hacking/testing purpose, it uses the RTL8187L.

**Comment by klange** [comment]
Isn't the RTL8187 a wireless chipset?

**Comment by hlechner** [comment]
Oh, yes, please forgive-me.

I associated your description of "network drivers" with "wireless drivers". but it was related to Ethernet.
