### ISSUE TITLE
Panel Improvement Ideas

### ISSUE THREAD

**Issue by klange** [klange/toaruos#109]
This ticket is for tracking a collection of ideas for improving the panel.
- [ ] Dynamically generate the background.
- [ ] Dynamically color icons, instead of drawing them directly as PNGs.
- [ ] Support widgets as separate applications.
- [x] Add a network status widget.

**Comment by makerimages** [comment]
- [ ] Allow to hide app titles, maybe?

**Comment by DemHydraz** [comment]
Allow spawning a new panel and piping stuff into it? (like dmenu)
