### ISSUE TITLE
Add patch to build gcc-4.6.4 with gcc-5 and newer

### ISSUE THREAD

**Issue by tuankiet65** [klange/toaruos#110]
Building gcc-4.6.4 (the bundled gcc in the toolchain) with gcc-5 or newer will cause the build process to fail:
```
In file included from /home/tuankiet65/sources/toaruos/toolchain/tarballs/gcc-4.6.4/gcc/cp/except.c:912:0:
cfns.gperf: At top level:
cfns.gperf:101:1: error: ‘gnu_inline’ attribute present on ‘libc_name_p’
cfns.gperf:26:14: error: but not here
```
Relevant issue: DragonFlyBSD/DPorts#136
More infomation and the patch to apply can be found here: https://gcc.gnu.org/ml/gcc-patches/2015-08/msg00375.html

**Comment by klange** [comment]
The linked patch modifies both the header file where this problem exists as well as the gperf source, which can cause Make to try to rebuild the header with `gperf`. To avoid this (as `gperf` is not in our dependency list and I do not wish to add it) I am only patching the header.

**Comment by klange** [comment]
... which did not work as intended. Okay, we'll add gperf...
