### ISSUE TITLE
Heap error: infinite loop with write (e.g. 'yes')

### ISSUE THREAD

**Issue by Saruta** [klange/toaruos#116]
`
Kernel Assertion Failed: <heap_end + increment <= KERNEL_HEAP_END -1> && "The kernel has attempted to allocate beyond the end of its heap."
`

**Comment by klange** [comment]
I don't think this is in the TTY layer, which should be stable, but rather something further up with the terminal and Yutani. The packet exchange API used by the compositor isn't the most stable, and has no limits on memory usage, so it is likely exhausting all of the available kernel heap building packets. Repeated output of line feeds causes a lot of redraw requests by the terminal, which means lots of packets...

**Comment by Saruta** [comment]
Indeed, I took a look. It seems to be a memory leak in the packet exchange API.
