### ISSUE TITLE
Memory leaks in net.c

### ISSUE THREAD

**Issue by cycl0ne** [klange/toaruos#118]
I see alot of mallocs without a free(). Seems you loose some memory when you send some packets around:
exp:
```
static int net_send_tcp(struct socket *socket, uint16_t flags, uint8_t * payload, uint32_t payload_size) {
	struct tcp_header *tcp = malloc(sizeof(struct tcp_header) + payload_size);
.....
	if (payload) {
		memcpy(tcp->payload, payload, payload_size);
	}

	return net_send_ip(socket, IPV4_PROT_TCP, tcp, sizeof(struct tcp_header) + payload_size);
}
```

and in net_send_ip().. the same.. a malloc and payload gets copied, but no free. same then with the other functions being called. malloc, copy.. again. Maybe you should add a free(payload) after memcpy().

Cheers
C.

**Comment by klange** [comment]
Can you file the MTU issues separately? It is known that we're not respecting any advertised MTUs, but we do split things up ourselves to very small amounts and I believe we're requesting a small MTU on our outgoing packets but I'd have to doublecheck.

**Comment by cycl0ne** [comment]
Done. Changed title, removed the MTU text and put it into an own Issue.

**Comment by klange** [comment]
A good bit of work was done to eliminate leaks in the network stack during the PCNET driver project, and I believe we have been successful, so I am closing this.
