### ISSUE TITLE
Some signedness needs to happen for %d

### ISSUE THREAD

**Issue by davidsilveiro** [klange/toaruos#121]
Within:

**1. toaruos-master/userspace/core/ls.c:142
2. toaruos-master/userspace/core/ls.c:145
3. toaruos-master/userspace/core/ls.c:147**

Example fix:

**printf("[%d]", (signed) [Variable name])**

**Comment by klange** [comment]
You have the wrong solution to a real problem here. The format strings should be changed to reflect the unsigned nature of the values passed into them; casting the values to signed types only masks a possible warning.

**Comment by davidsilveiro** [comment]
Thanks for the tip @klange :)
