### ISSUE TITLE
Memory Leak within fetch.c

### ISSUE THREAD

**Issue by davidsilveiro** [klange/toaruos#122]
We've forgotten to use **fclose()** on **f** when using **fopen()** on **line 111** before the **return** on **line 154** within **userspace/net/fetch.c**

**Comment by klange** [comment]
Missing an `fclose` before an exit (return from main) does not leak memory. ToaruOS is pretty hacky, but userspace-allocated memory being leaked past the _end of execution_ is not something that would happen.
