### ISSUE TITLE
No uniform code style

### ISSUE THREAD

**Issue by io12** [klange/toaruos#129]
Toaruos has no established coding style. Various parts of the code have a completely different style. A tool such as clang-format can automate the fix of this.

**Comment by klange** [comment]
https://github.com/klange/toaruos/wiki/Styleguide

**Comment by io12** [comment]
From kernel/mem/mem.c:
```
void
kmalloc_startat(
    uintptr_t address
) {
    placement_pointer = address;
}
```
This doesn't match other parts of the code or the style guide.

**Comment by klange** [comment]
It's from the old styleguide and hasn't been updated. `clang-format` is unable to produce anything remotely close to the style set out in the styleguide. We have also tried several other tools with worse results.

**Comment by gerow** [comment]
`clang-format` does google style by default. Since it's just a matter of religion it's not like anyone would care too much if you switched :upside_down_face:
