### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by PoisonNinja** [klange/toaruos#136]
Building the toolchain using `make toolchain` fails currently. Some issues:

* env: python2: No such file or directory
* No package manager support

I can work on this and submit a pull request. I'll try not to break existing builds...

The python2 error can be ignored while building the toolchain.

**Comment by PoisonNinja** [comment]
Too many build issues, it's not worth pursuing this...

**Comment by gil0mendes** [comment]
Yup! Is really complicated adapt the build system to OS X, some time ago I suggested to convert the build system to scons but isn't a aim for the project.

**Comment by gil0mendes** [comment]
For me, this is a very important issue... I don't like use virtual machines to build the OS, the current workflow is very hard for macOS users!

**Comment by PoisonNinja** [comment]
If you have Mac OS, you can try building on Mac OS. My fork contains the work that I did so far

**Comment by gil0mendes** [comment]
Ok... I will try see that in the next days

**Comment by PoisonNinja** [comment]
In the end though, it's probably not worth it. Running QEMU in Mac is incredibly slow, due to the lack of KVM acceleration. Terminal is probably fine, but running the compositor slows QEMU down to a crawl.

**Comment by gil0mendes** [comment]
That's true, but you can use VirtualBox or similar... Now, there is a script for that ([run-virtualbox.sh](https://github.com/klange/toaruos/blob/master/util/run-virtualbox.sh))

**Comment by klange** [comment]
Note that script relies on `grub-mkrescue`, which is probably not a fun thing to install on macOS. We could probably adapt the automated package installation for homebrew. As for why some other things aren't building, that's a tougher problem to tackle.

**Comment by PoisonNinja** [comment]
GRUB is actually pretty easy to build from source. It's just cross
compiling things that's really hard.

On Dec 9, 2016 6:52 PM, "Kevin Lange" <notifications@github.com> wrote:

Note that script relies on grub-mkrescue, which is probably not a fun thing
to install on macOS. We could probably adapt the automated package
installation for homebrew. As for why some other things aren't building,
that's a tougher problem to tackle.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/klange/toaruos/issues/136#issuecomment-266163541>, or mute
the thread
