### ISSUE TITLE
Window Rendering Glitch

### ISSUE THREAD

**Issue by MajickTek** [klange/toaruos#139]
typing 'wallpaper' at Terminal and then immediately hitting CTRL+C creates weird glitches to the window manager/compositor; even the mouse
![screen shot 2016-12-23 at 7 30 13 pm](https://cloud.githubusercontent.com/assets/12192591/21464273/44d6b1ea-c946-11e6-91f3-baf34556ea3b.png)
p.s. if this issue has been reported already, let me know ;)

**Comment by MajickTek** [comment]
Also eventually the mouse stops working.

**Comment by MajickTek** [comment]
by the time I took the screen shot the mouse couldn't move at all!

**Comment by MajickTek** [comment]
Also no typing after CTRL-C'ing terminal-vga. (sorry if I'm spamming, I found a lot of issues!

**Comment by MajickTek** [comment]
typing 'nyancat CTRL+C nyancat' freezes toaruos

**Comment by klange** [comment]
You have posted several unrelated issues in one issue report. Please stop posting garbage.

First issue: You launched a new `wallpaper` and then killed it, leaving no wallpaper application. The compositor doesn't clear the screen needlessly, so you get ghosting as it doesn't have a background to draw over the last frame. This isn't an issue.

Second issue: You launched `terminal-vga`, presumably from a graphical session, and it stole the keyboard. Solution: Don't do that.

Third issue: I can not reproduce this in any situation.
