### ISSUE TITLE
genext2fs doesn't support the -B argument

### ISSUE THREAD

**Issue by aliceklipper** [klange/toaruos#140]
When I'm tried to run `make toolchain` on latest Arch (Manjaro), I got following output:

````
I am going to install some system packages. I will probably need you to provide a password.
If you don't want to do this and you're sure you have all of the required system packages, then interrupt the password prompt and run this script again with -q.
You are on an entirely unsupported system, please ensure you have the following packages:
  - essential development packages for your platform (C headers, etc.)
  - development headers for mpfr, libmpc, and gmp
  - gcc
  - YASM
  - genext2fs
  - autoconf/automake
  - wget
  - qemu
  - texinfo
  - pkg-config
  - git
  - ctags
(If you are on Arch, install: gcc yasm genext2fs base-devel wget mpfr libmpc gmp qemu autoconf automake texinfo pkg-config git ctags)

... then run this script (toolchain/toolchain-build.sh) again with the -q flag.
make: *** [Makefile:38: toolchain] Error 1
````

All of these packages was already installed. `genext2fs -V` outputs:

````
genext2fs 1.4.1
````

According to its website, this is the latest version.

When I'm tried to run `./toolchain/toolchain-build.sh -q` I got the following output:

````
Hold up!
Your genext2fs does not support the -B (--block-size) argument.
You can build a copy from the CVS HEAD which supports this:

    http://genext2fs.sourceforge.net/

````

So, is this ToaruOS issue (perhaps, it depends on outdated `genext2fs`), or Arch-specific?

**Comment by klange** [comment]
That "Hold up!" message is from me, telling you exactly what the problem is and how to fix it - you need to build `genext2fs` from the CVS HEAD provided on the website to get the `-B` option. Ultimately, I hope to replace `genext2fs` with something of my own which should obviate this issue.
