### ISSUE TITLE
Not possible to boot (VMWare Workstation 9.0.0 on Win 7)

### ISSUE THREAD

**Issue by kroiksm** [klange/toaruos#146]
Hello,

i tried to boot the ISO (https://github.com/klange/toaruos/releases/download/v1.0.2/toaruos.iso) as a Live-CD in my VMWare Workstation, v. 9.0.0, Windows 7 64bit. 

1) boot-menu is OK, it is possible to choose some boot-option
2) but after that the the booting stops and hung at "loading ramdisk"
Loading modules ...
Loading ramdisk ...

my virtual machine is OK, tested with other Live-CDs (Knoppix, Ubuntu), with 2 Gb of RAM

a) tried the options "LiveCD", "Normal graphical boot", "Graphical terminal"
b) if "VGA Text mode", than the system switchs to console-mode with cursor and hungs.

**Comment by kroiksm** [comment]
P.S.
a) tried the options "LiveCD", "Normal graphical boot", "Graphical terminal" 
b) if "VGA Text mode", than the system switchs to console-mode with cursor and hungs.

**Comment by klange** [comment]
VMWare Workstation is not a supported platform. The last time I used it, some issues with the PATA driver seemed to be at fault. Try disabling that module (it is not necessary to run a live CD). You can disable modules from the grub menu labeled "Configure optional boot modules". Unfortunately, as my trial of Workstation is expired, I can not invest time (and money) in investigating the underlying issue. If you can provide further diagnostic information, it may be helpful in figuring out what is wrong. Unhelpfully, VMWare Workstation goes to great lengths to obfuscate its hardware configurations, which makes it very difficult to deal with generally.

**Comment by kroiksm** [comment]
Now works, thank you, 
I disabled "ATA/ATAPI module" from GRUB menu

**Comment by klange** [comment]
I've pushed an actual fix which was successfully tested in VMWare Player 12. It should be available in the next release, alongside many other fixes for VMWare.
