### ISSUE TITLE
AzPainter 2.0.1 on ToaruOS 

### ISSUE THREAD

**Issue by Symbian9** [klange/toaruos#149]
Please, try compile and run **AzPainter 2.0.1** - full color image editor 
* Website - http://azsky2.html.xdomain.jp/linux/azpainter/index.html
* Released: 7 FEB 2017
* Source code - https://osdn.net/projects/azpainter/releases/67071

Blogs:
* official - http://azsky2.html.xdomain.jp/memo/index.html
* unofficial - https://aznosekai.wordpress.com/

![Opening complete PSD in AzPainter](http://i.imgur.com/xMDEWzg.png)

References:
* https://www.linux.org.ru/news/multimedia/13216485
* https://www.linux.org.ru/forum/multimedia/12283767

**Comment by klange** [comment]
This an X11 application written against Xlib. It will never be portable to ToaruOS.

**Comment by Symbian9** [comment]
Never say "never"... :)
