### ISSUE TITLE
Building and running initial commit

### ISSUE THREAD

**Issue by qubbit** [klange/toaruos#150]
How does one run the kernel executable from initial commit?

I was able to run `make` and produce the executable no problem under ubuntu :)

**Comment by klange** [comment]
If you followed all of the instructions in the toolchain build, you may run `make run` to launch a QEMU VM from the development environment.

**Comment by klange** [comment]
Please do not report issues on code that is six years old.

**Comment by qubbit** [comment]
I wanted to see your progress with time as a way to learn on my own. Thank you for the pointer.

**Comment by klange** [comment]
You'll hit a roadblock if you progress through the git history, as at some point I started working on a userspace toolchain and it took about a year for it to make it into the git repo, despite being used throughout all that time.

**Comment by qubbit** [comment]
Ahhh, in that case I will start with OS Dev Wiki. Thanks man.
