### ISSUE TITLE
soy nuevo

### ISSUE THREAD

**Issue by pablo1212** [klange/toaruos#151]
me pide contraseña pa instalar  cual es

**Comment by tomasnoliveira** [comment]
From here: [link](https://github.com/klange/toaruos/releases/tag/v1.0.0)

> The default user on both the CD and development hard disks is local with password local. You may also make use of the root user, with password toor, but a sudo implementation is available if you need to perform privileged tasks as a regular user.

Por favor use el inglés, o nadie entenderá usted, gracias.

**Comment by klange** [comment]
Both the boot menu:

![grub](http://i.imgur.com/wKSxbZ0.png)

... and the tutorial:

![tutorial](http://i.imgur.com/2V9OL3P.png)

... clearly inform you of the default username and password for the live CD.
