### ISSUE TITLE
Memory usage too high

### ISSUE THREAD

**Issue by cr6void** [klange/toaruos#153]
Hi,

Sorry, I have another suggestion: the memory usage of your OS.

When I launch the terminal and run "free -u" I can see 150MB of memory used !

Your "hobby OS" has only very limited functionalities, but 150MB is **surprisingly more** than the actual linux system I use.

Strange...

**Comment by klange** [comment]
You are running a live CD system with a 64MB ramdisk, running a compositor, on an OS without COW support, running several Python processes. There is nothing particularly high about the memory usage given the circumstances.

**Comment by klange** [comment]
I should be clear, I'm closing this because I don't consider 150MB to be issue-worthy memory usage. There are definitely areas where we can improve memory usage, but this is perfectly expected behavior as it is, and very much within reason for the system in its current state.
