### ISSUE TITLE
Installing Python 3.6

### ISSUE THREAD

**Issue by srs1978** [klange/toaruos#154]
Since you're requiring 3.6 and the most common 16.04 doesn't have that by default ...

    sudo add-apt-repository ppa:jonathonf/python-3.6
    sudo apt-get update
    sudo apt-get install python3.6

**Comment by klange** [comment]
This isn't portable outside of Ubuntu, so I don't want to add something like this to the build scripts which also work on Debian. At the moment, I am considering adding a manual build of 3.6 from sources, since we already have them available in the build.

**Comment by srs1978** [comment]
I was more thinking of a document hint, but probably a local build would work great. Perhaps pyenv?

**Comment by klange** [comment]
Closing this for now until I get around to a manual install. I've added a check/warning to `toolchain/install-python.sh` which mentions the PPA.
