### ISSUE TITLE
pushd: too many arguments

### ISSUE THREAD

**Issue by RogueAI42** [klange/toaruos#157]
On my Arch system, the build scripts fail out of the box with "pushd: too many arguments" on line 163 of install.sh. I investigated this, and it seems that my system is resolving "zlib*" to both the extracted directory and the tarball itself. Changing the line from

`pushd $DIR/tarballs/zlib*`

to

`pushd $DIR/tarballs/zlib*/`

fixed it for me, but I'm submitting this as an issue rather than a PR in case it causes trouble on one of the supported hosts.

**Comment by klange** [comment]
Weird. Bash consistently accepts only the first argument to `pushd` for me and never complains about the other ones. I highly doubt that's a Debian patch, but... weird. I also use a glob for Mesa, so I've added the trailing `/` to that as well.

**Comment by DexHen** [comment]
Hi, 
I faced the same problem today, and it took me some time to figure out the source of the problem, 
the problem was caused with the directory name, it should not contain any space.
I removed the spaces and it worked for me.
Hopefully this will help someone
