### ISSUE TITLE
Investigate issues with booting from disk

### ISSUE THREAD

**Issue by klange** [klange/toaruos#158]
Inconsistent issues in Python with booting from disk that were not present during early 1.0 testing, not sure of the cause yet. `login.py` in particular is failing in a few different ways on different builds.

**Comment by ComputeLinux** [comment]
even though booting doesn't work, I'd like some way to set a hard drive as the main drive instead of using a tempfs, so I can keep my work.

**Comment by klange** [comment]
I do want to look into overlay filesystems, so that a live CD's content could be supplemented with changes and new files from a persistent source, but resolving the issues with booting from an ext2 partition on a disk is more important.

**Comment by ComputeLinux** [comment]
Fair enough, It's obviously stopping quite a bit of progress.
