### ISSUE TITLE
No gui in VirtualBox and qemu

### ISSUE THREAD

**Issue by articice** [klange/toaruos#159]
Hi!

I've downloaded the 1.1.2 iso from https://github.com/klange/toaruos/releases/tag/v1.1.2
and I consistently get the same result in both VirtualBox and qemu - after boot there's a black screen and the mouse pointer leaves a trace on it when moving around.

**Comment by klange** [comment]
1. Why are you running 1.1.2?
2. How much RAM did you give your VM?

**Comment by articice** [comment]
1. That's the newest I could find. Is it not?
2. Tried 2Gb and more, up to 128Mb for video memory
3. I've tried qemu-system-x86_64 -vga std -m 2048 and witohut it.
4. Selected Other/Unknown, tried enabling APIC, no PAE, chipset PIIX3, PS2 mouse
5. Qemu 2.8.0, VirtualBox 5.1.18_Gentoo r114002

**Comment by klange** [comment]
The newest is 1.2.1, 1.1.2 was released in March. I am unable to reproduce your issue. On my hardware (Core i5-6300 @ 2.4GHz), with the same version of QEMU (2.8.0) and using the same arguments (eg., no KVM), I see a mouse cursor approximately 18 seconds after selecting the boot option from GRUB, and after 30 seconds the welcome screen appears (the desktop takes several more seconds to appear). With KVM, the desktop takes approximately 4-5 seconds (mostly waiting for GRUB to load the ramdisk). 
VirtualBox does support a software-only emulation mode, which takes approximately 30 seconds to display a mouse cursor in 1.2.1, and 55 seconds to show the welcome screen.

If you could provide a description of your hardware and try with KVM (and verify whether VirtualBox is running with VT-x support), that would be helpful.

**Comment by klange** [comment]
Any updates on this?

**Comment by articice** [comment]
@klange sorry, yes, it's fine, downloaded 1.2.1 and it worked fine.
Although, I did get a mouse pointer trace first, the GUI appeared later.

**Comment by klange** [comment]
Especially with the newer builds, where the root filesystem is migrated by a Python script, I would expect as much on a slow setup. Glad things are working, though!
