### ISSUE TITLE
toaruos.iso

### ISSUE THREAD

**Issue by dreamersoftware** [klange/toaruos#160]
Already Compile, _cdrom generate inside not see .iso aleady use the all instruccions.

how to create the iso file?

**Comment by klange** [comment]
You are missing so much critical information. I can not help you without know what environment you are in, what exactly you did, and what the output was. What instructions are you following? Under what OS?

**Comment by dreamersoftware** [comment]
I use ubuntu 16.04.3 TLS desktop and Windows Subsystem

When the ouput say cd rom créate but the folder _cdrom os empty

K Lange <notifications@github.com> escreveu em ter, 24/10/2017 às 13:59 :

**Comment by klange** [comment]
What commands are you running? What instructions are you following? You haven't answered half of my questions.

**Comment by dreamersoftware** [comment]
first download the source code from klange/release and download ISO file
1) Extract the source Code in toaruos
2) install python3.6
3) install build-essential
4) make toolchain
5) toolchain/install-phyton.sh
6) toolchain/install-pycairo.sh
7) make
8) make cdrom

Make create the kernel and Image.The first erro the image create but say
inode too low
Make cdrom create the folder _cdrom in the folder contain boot, mod,
wallpaper, kernel and disk.img say "CD generated"

The information say Create iso but not create toaruos.iso

next try
docker pull toaruos/build-tools:test
docker run -v `pwd`:/opt/tree -w /opt/tree -t toaruos/build-tools:test
util/build-travis.sh

the problem is the same.

thanks




K Lange <notifications@github.com> escreveu em qua, 25/10/2017 às 01:00 :

**Comment by klange** [comment]
These instructions are not correct for building CDs from scratch, as described [on the wiki](https://github.com/klange/toaruos/wiki/Building-and-Running#building-cds-instead).

Steps 1-6 will get you a working toolchain and allow you to build a hard disk image within that checkout of the source code, but you will need a separate copy of the repository to actually build CDs, as the toolchain build process installs several files to the `hdd` directory which will not work when building ramdisk images for the CD.

Additionally, you will need `grub-pc-bin` and `xorriso` to build CD images.

**Comment by klange** [comment]
I am not sure if it is because of line feeds added by your email client (please stop replying to these issue reports by email - use the Github web interface), but you also say you tried to run the docker image and your email suggests you may have just run the container with nothing and then ran `util/build-travis.sh`. Either way, to my knowledge, Docker does not work on WSL, so I don't expect that to work for you.

**Comment by dreamersoftware** [comment]
ok in the wiki not say how to past information to xorriso or grub-pc-bin

2017-10-25 7:38 GMT+01:00 K Lange <notifications@github.com>:

**Comment by klange** [comment]
`make cdrom` uses `grub-mkrescue` which will call `xorriso`; you need to have them installed, but you are not going to call them yourself.

**Comment by dreamersoftware** [comment]
ok thanks let me try

2017-10-25 7:48 GMT+01:00 K Lange <notifications@github.com>:

**Comment by dreamersoftware** [comment]
Hello the problem is the inode to create ram disk

K Lange <notifications@github.com> escreveu em qua, 25/10/2017 às 08:48 :

**Comment by klange** [comment]
The inode count message from `genext2fs` is a warning, not an error, and should not impede the build process. Please post the entire output of your build so I may examine it.

**Comment by klange** [comment]
Also, please stop sending comments by email - use the Github web interface.

**Comment by dreamersoftware** [comment]
how to send the log?

2017-10-26 7:57 GMT+01:00 K Lange <notifications@github.com>:

**Comment by klange** [comment]
Go to the Github site as linked in the emails you keep replying to, copy the output of your terminal to a file, and then attach it to a comment on this issue report.

**Comment by dreamersoftware** [comment]
make cdrom
   CC   modules/testb.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/testb.c [module]
   CC   modules/rtl.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/rtl.c [module]
   CC   modules/tmpfs.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/tmpfs.c [module]
   CC   modules/ps2kbd.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ps2kbd.c [module]
   CC   modules/net.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/net.c [module]
   CC   modules/ac97.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ac97.c [module]
   CC   modules/test.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/test.c [module]
   CC   modules/vidset.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/vidset.c [module]
   CC   modules/ata.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ata.c [module]
   CC   modules/usbuhci.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/usbuhci.c [module]
   CC   modules/dospart.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/dospart.c [module]
   CC   modules/vgadbg.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/vgadbg.c [module]
   CC   modules/procfs.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/procfs.c [module]
   CC   modules/snd.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/snd.c [module]
   CC   modules/xtest.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/xtest.c [module]
   CC   modules/zero.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/zero.c [module]
   CC   modules/ext2.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ext2.c [module]
   CC   modules/lfbvideo.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/lfbvideo.c [module]
   CC   modules/vgalog.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/vgalog.c [module]
   CC   modules/debug_shell.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/debug_shell.c [module]
   CC   modules/hda.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/hda.c [module]
   CC   modules/serial.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/serial.c [module]
   CC   modules/test-write.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/test-write.c [module]
   CC   modules/pcspkr.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/pcspkr.c [module]
   CC   modules/iso9660.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/iso9660.c [module]
   CC   modules/random.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/random.c [module]
   CC   modules/e1000.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/e1000.c [module]
   CC   modules/ataold.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ataold.c [module]
   CC   modules/crash.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/crash.c [module]
   CC   modules/ps2mouse.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/ps2mouse.c [module]
   CC   modules/pcnet.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/pcnet.c [module]
   CC   modules/vmware.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/vmware.c [module]
   CC   modules/vboxguest.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/vboxguest.c [module]
   CC   modules/packetfs.c [module]fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
   CC   modules/packetfs.c [module]
  ext   Generating a ramdisk image...number of inodes too low, increasing to 5840
genext2fs: couldn't allocate a block (no free space)
Makefile:417: recipe for target '_cdrom/ramdisk.img' failed
make: *** [_cdrom/ramdisk.img] Error 1
dreamer@ubuntuserv2:~/toaruos$

**Comment by klange** [comment]
I don't think you followed my instructions. There are several thing wrongs with this output.

**Comment by klange** [comment]
Please discard your current build environment and start from scratch, following these instructions:

```bash
sudo apt-get install grub-pc-bin xorriso
git clone https://github.com/klange/toaruos toaruos-base
cd toaruos-base
make toolchain
. toolchain/activate.sh
make
toolchain/install-python.sh
toolchain/install-pycairo.sh
make clean-disk; make
cd ..
git clone toaruos-base toaruos-iso
cd toaruos-iso
toolchain/install-python.sh
toolchain/install-pycairo.sh
make cdrom
```
