### ISSUE TITLE
Will you add a browser to ToaruOS?

### ISSUE THREAD

**Issue by ashuradev** [klange/toaruos#165]
?

**Comment by klange** [comment]
ToaruOS has a browser, it's just a bit hidden as it's part of the help document viewer as its HTML rendering is not quite complete enough to be useful to most people:

![screenshot](https://i.imgur.com/WqRUXMi.png)

There's always interest in porting a more complete third-party rendering engine, such as Webkit, but this is a monumental task.

**Comment by BlackPhrase** [comment]
It skips CSS styles as I can see

What about Gecko? I know that it currently runs a like a **** and consumes a lot of RAM unnecesary but I still hope they'll fix it someday

**Comment by klange** [comment]
Webkit is probably an easier port as it's seen a lot more platforms, but I would love Gecko. Either way, modern rendering engines are very complex beasts. We might do well to look at some very old versions of Gecko, Webkit, and KHTML to see if they are more suitable for porting. Meanwhile, I'm busy with [another project](https://github.com/klange/toaru-nih) at the moment.

**Comment by BlackPhrase** [comment]
I recently compared performance of Firefox 6.01 with latest Nightly and it was drastic
FF6 is flying with 30+ open at once and consuming 500 Mb of RAM
(But some features and stylings are, of course, broken)
In same conditions Nightly would probably freeze and consume the whole 1 Gb
My recent idea was to take that FF6 codebase and provide some modern features support

**Comment by zesterer** [comment]
@BlackPhrase Therein lies the problem. Those modern features account for most of the performance losses. Sure, there generally exists a tradeoff between speed and memory consumption in most software problems but it is necessary to choose either one or the other.

**Comment by ashuradev** [comment]
Thanks

**Comment by generatyggss** [comment]
Hello klange,
I`m pretty interested in ToaruOS and i also run it on real hardware and stuff. I´d like to know if there is a browser with I can access the Internet with (and how to do it) and if you could publish a browser build (package) for ToaruOS like NetSurf or other lightweight ones, i would be willing to help.
