### ISSUE TITLE
C++ support?

### ISSUE THREAD

**Issue by BlackPhrase** [klange/toaruos#166]
Does ToaruOS support it?

**Comment by klange** [comment]
In userspace? Yes, but the C++ standard library isn't built shared, so C++ applications must be built statically; additionally, I believe a large number of the native library headers need to be included within `extern "C"` blocks as they don't do that themselves. There is a sample [here](https://github.com/klange/toaruos/blob/master/userspace/tests/test-c%2B%2B.c%2B%2B).

**Comment by BlackPhrase** [comment]
Thx
I'm planning to work on this
https://github.com/klange/uiharu

**Comment by klange** [comment]
Uiharu is a bunch of really terrible [Python](https://github.com/klange/toaruos/blob/master/userspace/py/lib/text_region.py) at the moment, and writing anything for it in C++ is highly discouraged, as the lack of a shared C++ library means C++ code can not be used in Python modules, which are critical to the ToaruOS desktop in its current form.

**Comment by BlackPhrase** [comment]
So there is some implementation of it already present?
Are the contents of "py/lib/" folder is fully related to uiharu impl?

**Comment by klange** [comment]
No, only the linked library is directly related to the HTML renderer.

**Comment by klange** [comment]
Then you're not "implementing the uiharu", you're writing your own HTML renderer. Uiharu already exists, and is written in Python. It's vaguely capable of rendering this page.

![screenshot_2018-04-17_20-24-48](https://user-images.githubusercontent.com/223546/38866929-7248f8f2-427d-11e8-850c-a3e789a9e482.png)

**Comment by BlackPhrase** [comment]
Yep, I mean that I'm planning to implement the rest in C++
Or it would be better not to do that?

**Comment by klange** [comment]
It would be literally incompatible (C++ libraries can not be used with Python in ToaruOS), and I am not looking for someone to contribute to that project.

**Comment by BlackPhrase** [comment]
Actually, calling C++ from Python is possible if I remember right
Also:
https://stackoverflow.com/questions/145270/calling-c-c-from-python

Or you mean that ToaruOS version of Python can't do that?

btw, am I remember correctly that some userspace components are implemented in Python? (I dunno which of them, exactly, though)

**Comment by klange** [comment]
It is not possible *in ToaruOS* because the C++ standard library is not build shared.

Almost all of ToaruOS's desktop is implemented in Python, save for the terminal emulator which remains C.

**Comment by BlackPhrase** [comment]
>It is not possible in ToaruOS because the C++ standard library is not build shared.

I'm ignoring this for now

>and I am not looking for someone to contribute to that project.

Oh, I see

**Comment by BlackPhrase** [comment]
Also, there is a possibility to provide C API using only POD types

**Comment by BlackPhrase** [comment]
Oh, yeah
What do you think about C API and Python binding (a bunch of wrapper classes that will be accessing that API)?

**Comment by klange** [comment]
Python bindings over C libraries are a fundamental part of how most of mainline ToaruOS's desktop works. Most of them are written in Python using `ctypes`, but writing CPython modules is probably the best approach (and CPython modules should build correctly with the toolchain - see how we build the Cairo module).

**Comment by BlackPhrase** [comment]
Yep, I wasn't sure but without a dynamic C++ stdlib support this looks like a single option
Ok, thanks
