### ISSUE TITLE
Potential memory leaks in linker.c

### ISSUE THREAD

**Issue by ZanyXDev** [klange/toaruos#195]
In function   [static elf_t * open_object(const char * path)](https://github.com/klange/toaruos/blob/master/linker/linker.c#L180)
used ` FILE * f = fopen(file, "r");` without `fclose(f)`

**Comment by klange** [comment]
The pointer is [stored] and eventually [`fclose`d in `do_actual_load`](https://github.com/klange/toaruos/blob/master/linker/linker.c#L589)
