### ISSUE TITLE
fatal error: kuroko/kuroko.h: No such file or directory

### ISSUE THREAD

**Issue by adnan-repo** [klange/toaruos#200]
I'm building toaruos from source but following error occurs after running make in the project folder:

`i686-pc-toaru-gcc -O3 -s -std=gnu99 -I. -Iapps -pipe -mmmx -msse -msse2 -fplan9-extensions -Wall -Wextra -Wno-unused-parameter   -o base/bin/kuroko apps/kuroko.c -ltoaru_rline -lkuroko -ltoaru_kbd
apps/kuroko.c:24:27: fatal error: kuroko/kuroko.h: No such file or directory
 #include <kuroko/kuroko.h>
                           ^
compilation terminated.
.make/kuroko.mak:2: recipe for target 'base/bin/kuroko' failed
make: *** [base/bin/kuroko] Error 1
`

Enviornment : Ubuntu 18.04 (Bionic)

**Comment by klange** [comment]
Somewhat recently a submodule was introduced to the repository. You will need to run `git submodule update --init` to clone the submodule, or add `--recursive` when cloning the repository.

**Comment by hello01-debug** [comment]
I had to manually clone the repository, it said that the repository did not exist when I ran git with --recursive.
