### ISSUE TITLE
Recommended QEMU uses deprecated options

### ISSUE THREAD

**Issue by eryjus** [klange/toaruos#221]
![image](https://user-images.githubusercontent.com/2507650/139565044-6d939b7d-28c3-49d9-97c6-dfd1aae9348b.png)

Update the instructions?

Host system:
$ uname -a
Linux [snip] 5.14.13-200.fc34.x86_64 #1 SMP Mon Oct 18 12:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klange** [comment]
QEMU has no stable command line flags and they deprecate options every week. I can't keep up.

**Comment by minhtran83** [comment]
@klange Do we have instruction for running qemu on MacOS?

**Comment by klange** [comment]
I guess you'd want `-accel hvf`? https://wiki.qemu.org/Features/HVF

I would also recommend VirtualBox, as I know it has hardware virtualization support on Intel Macs. For M1, I don't know what the current recommendation is for x86 virtual machines.

**Comment by TobiX** [comment]
QEMU 8 has finally removed `-soundhw`, so you need to use `-device ac97` now (which has worked like that since at least qemu 5.x)

**Comment by klange** [comment]
`-device ac97` is incorrect. The device name is `AC97`, and is case sensitive.
