### ISSUE TITLE
 unable to build toolchain

### ISSUE THREAD

**Issue by mnisk** [klange/toaruos#224]
got this error while building cross-compiler
i used this command = bash util/build-toolchain.sh

http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
make: *** No rule to make target 'all-gcc'.  Stop.
make: *** No rule to make target 'install-gcc'.  Stop.
make: *** No rule to make target 'all-target-libgcc'.  Stop.
make: *** No rule to make target 'install-target-libgcc'.  Stop.
x86_64-pc-toaru-as -o base/lib/crt0.o libc/arch/x86_64/crt0.S
make: x86_64-pc-toaru-as: Command not found
x86_64-pc-toaru-gcc -O2 -std=gnu11 -Wall -Wextra -Wno-unused-parameter -fPIC -c -o libc/main.o libc/main.c
make: x86_64-pc-toaru-gcc: Command not found
make: *** [Makefile:190: libc/main.o] Error 127
make: *** No rule to make target 'all-target-libgcc'.  Stop.
make: *** No rule to make target 'install-target-libgcc'.  Stop.
x86_64-pc-toaru-as -o base/lib/crt0.o libc/arch/x86_64/crt0.S
make: x86_64-pc-toaru-as: Command not found
x86_64-pc-toaru-gcc -shared -nostdlib -fPIC -o base/lib/libm.so util/libm.c
make: x86_64-pc-toaru-gcc: Command not found
make: *** [Makefile:209: base/lib/libm.so] Error 127
mak@mak-VirtualBox:~/Downloads/toaruos$ bash util/build-toolchain.sh

**Comment by klange** [comment]
Hi, I no longer provide support for users trying to build a local toolchain, as the process is very dependent on your host environment and the parts that need to be built are just gcc and binutils (the rest requires local package installation for the handful of utilities still in use by the Makefile to author a working CD image).

If you are just looking to try out the latest git HEAD, there is a CI pipeline that builds every commit and uploads the resulting CD image as an artifact: https://github.com/klange/toaruos/actions/runs/1479393349

If you want to make changes and build locally, please use the Docker container. Retrieving and running it is much faster than building gcc and binutils and getting all the other various tools.

By the way, the error message you quoted includes a link to instructions to resolve your problem.
