### ISSUE TITLE
Install without docker

### ISSUE THREAD

**Issue by 17lwinn** [klange/toaruos#237]
Hi- I'm interested in trying this but what I plan to try it on does not allow docker. I want to use QEMU so how would I be able to get this running if this is even possible?

**Comment by klange** [comment]
Docker is only part of the build process, and you do not need to build ToaruOS from source to run it. Prebuilt CD images are attached to [tagged releases](https://github.com/klange/toaruos/releases/tag/v2.0.1) and also uploaded as [build artifacts](https://github.com/klange/toaruos/actions/runs/1879034454) by CI with every push, though I do not recommend using the latest master builds. Instructions for running the CD image in various virtual machines are provided [in the README](https://github.com/klange/toaruos#running-toaruos).

**Comment by 17lwinn** [comment]
Hi- so if I made some changes and wanted to build what do I do?

**Comment by klange** [comment]
What changes do you want to make?

The build requires a cross compiler toolchain (GCC and Binutils targeted to the OS) and a number of utilities. The Docker image is a shortcut to obtaining those, and is used by the CI builders. You can attempt to install the required packages following the same steps used to build the Docker images, but it can take multiple hours to build the required tools. I no longer provide instructions for this, as the necessary packages are prone to name changes in distribution repositories so my instructions are regularly outdated even for Ubuntu, and the gcc/binutils builds are not special beyond the patches for the OS target so they're far more dependent on the host environment.

You can also fork the repository and push your changes to your own copy and Github will run the CI tasks for you.

**Comment by 17lwinn** [comment]
I'll give forking a try, thanks!
