### ISSUE TITLE
Kernel crash on "sudo rm -r /var/sudoers".

### ISSUE THREAD

**Issue by Doczom** [klange/toaruos#251]
From turbocat2001:

> If you remove the existing /var/sudoers directory as root, the kernel will crash.

**Comment by klange** [comment]
Prior to ebd55bc204f8a539f019660dfe8481c4f4928e80, trying to delete _any_ directory kernel panicked. This should be resolved already.

**Comment by turbocat2001** [comment]
Thanks for unbanning. I will be more restrained. Yes indeed it has been fixed. Sorry...
