### ISSUE TITLE
I cant build, help please.

### ISSUE THREAD

**Issue by ghost** [klange/toaruos#27]
I'm following [this](https://travis-ci.org/klange/osdev) page to build kernel, 

But when I execute ./.build-travis.sh, here is what happens:

```
bekir@ubuntu:~/klange/osdev$ sudo ./.build-travis.sh 
/home/build/osdev/toolchain ~/klange/osdev
~/klange/osdev
   CC   ./gui/ttk/lib/ttk-core.cIn file included from ./gui/ttk/lib/ttk-core.c:10:0:
./gui/ttk/ttk.h:7:19: fatal error: cairo.h: No such file or directory
compilation terminated.
   CC   ./gui/ttk/lib/ttk-core.c
/home/bekir/klange/osdev/userspace/gui/ttk/lib/ttk-core.o 1
['i686-pc-toaru-gcc', '-std=c99', '-U__STRICT_ANSI__', '-O3', '-m32', '-Wa,--32', '-g', '-I.', '-I/home/build/osdev/toolchain/local/i686-pc-toaru/include/freetype2', '-I/home/build/osdev/toolchain/local/i686-pc-toaru/include/cairo', '-I/home/build/osdev/toolchain/local/i686-pc-toaru/include/pixman-1', '-c', '-o', '/home/bekir/klange/osdev/userspace/gui/ttk/lib/ttk-core.o', './gui/ttk/lib/ttk-core.c']
Traceback (most recent call last):
  File "build.py", line 220, in <module>
    source_obj.run()
  File "build.py", line 108, in run
    raise Exception
Exception
make: *** [.userspace-check] Error 1
bekir@ubuntu:~/klange/osdev$ 
```

**Comment by tsitso321** [comment]
I have a problem i cant seem to go through

 File "build.py", line 157, in <module>
    sources[os.path.abspath(source)] = compiler(source)
  File "build.py", line 56, in __init__
    self.includes, self.libs = self._depends()
  File "build.py", line 86, in _depends
    depends = self._calculate([], depends)
  File "build.py", line 75, in _calculate
    depends = self._calculate(depends, other)
  File "build.py", line 75, in _calculate
    depends = self._calculate(depends, other)
  File "build.py", line 75, in _calculate
    depends = self._calculate(depends, other)
  File "build.py", line 75, in _calculate
    depends = self._calculate(depends, other)
  File "build.py", line 74, in _calculate
    _, _, other = self.dependency_hints[k]
KeyError: ''

**Comment by klange** [comment]
You are responding to a closed issue about an unrelated problem. If you have a different issue with the build tools, please file a separate ticket.
