### ISSUE TITLE
init: double fd 1 and no fd 2

### ISSUE THREAD

**Issue by predefine** [klange/toaruos#282]
https://github.com/klange/toaruos/blob/e24cdc168170d0fa4c49d150376c09a6924fae23/apps/init.c#L47-L51

**Comment by klange** [comment]
I believe you are mistakenly interpreting the arguments to `syscall_open`. The second argument is the flags value, with `1` being `O_WRONLY`.

**Comment by predefine** [comment]
sorry, i think it was fd
