### ISSUE TITLE
docker 400 error

### ISSUE THREAD

**Issue by cbrown7752** [klange/toaruos#285]
Error: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "util/build-in-docker.sh": stat util/build-in-docker.sh: no such file or directory: unknown

**Comment by klange** [comment]
It sounds like you ran docker from the wrong directory.

**Comment by cbrown7752** [comment]
I rent it from both the main directory and the utils docker directory. Both pull the same error

**Comment by klange** [comment]
What is the complete command you are running?

**Comment by cbrown7752** [comment]
docker run -v pwd:/root/misaka -w /root/misaka -e LANG=C.UTF-8 -t toaruos/build-tools:1.99.x util/build-in-docker.sh

**Comment by klange** [comment]
If that is the command you are running, you have critical typo. The backticks around `pwd` are important.

**Comment by cbrown7752** [comment]
It has said that those weren't a part of the doctor system which is why I had taken them out

**Comment by klange** [comment]
That's a simple Unix shell command, the backticks have nothing to do with Docker. You need to start Docker with a bind mount of the repository or none of this will work.

**Comment by cbrown7752** [comment]
i still get this `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "util/build-in-docker.sh": stat util/build-in-docker.sh: no such file or directory: unknown.`

**Comment by klange** [comment]
What are you running this under?

I am not in the business of providing support for Docker. If you can not get the container to work locally, fork the repository and Github CI will do it for you and provide you with the resulting ISO as a build artifact.

**Comment by cbrown7752** [comment]
Being ran in the main directory

**Comment by klange** [comment]
I mean what environment are you running this? I'm wondering if you're using a Windows host - neither cmd.exe nor PowerShell support backticks the way a Unix shell would, so they would not be binding the right directory.

**Comment by cbrown7752** [comment]
That's what I was using when I originally started and the one I prefer to use but have since moved to a Linux laptop

**Comment by klange** [comment]
The full Docker commands from the README should work on Linux if you have Docker set up - this is what the Github CI runs with every commit. I'll repeat my suggestion that if you want to try building from source you can fork the repo and have Github do it for you.

If you want try again from Windows, I looked into this for someone in a previous issue report and you may be able to replace the `-v ...` option with `-v "/${PWD}:/root/misaka"` and get it working in PowerShell.
