### ISSUE TITLE
Failed to execute /bin/init

### ISSUE THREAD

**Issue by cbrown7752** [klange/toaruos#289]
![PXL_20231117_232539247.jpg](https://github.com/klange/toaruos/assets/59544410/d516592f-61e0-4029-b855-d5ce9983e6ce)

Seem to be having an issue with install constantly get this issue no matter what device I tried to install on

**Comment by klange** [comment]
How exactly are you “installing” it? You are missing the ramdisk.

**Comment by klange** [comment]
Closing this because I have an active DMCA complaint against the user who filed this issue for violation of ToaruOS’s license terms.
