### ISSUE TITLE
I Need Some Help. To Recompile this project after some modifications.

### ISSUE THREAD

**Issue by TunifyBasic** [klange/toaruos#293]
after compiling and running the kernel for the first time doing some modification then trying to recompile it i got this error:
```
$ sudo docker run -v `pwd`:/root/misaka -w /root/misaka -e LANG=C.UTF-8 -t toaruos/build-tools:1.99.x util/build-in-docker.sh 
ln: failed to create symbolic link 'util/local/gcc_local': File exists
x86_64-pc-toaru-gcc -O2 -std=gnu11 -ffreestanding -Wall -Wextra -Wno-unused-parameter -z max-page-size=0x1000 -fPIC -c -o libc/main.o libc/main.c
make: x86_64-pc-toaru-gcc: Command not found
make: *** [Makefile:138: libc/main.o] Error 127
```
i also tryied:
```
$ make
x86_64-pc-toaru-gcc -O2 -std=gnu11 -ffreestanding -Wall -Wextra -Wno-unused-parameter -z max-page-size=0x1000 -fPIC -c -o libc/main.o libc/main.c
make: x86_64-pc-toaru-gcc: Command not found
make: *** [Makefile:138: libc/main.o] Error 127
```
also i wonder how could i compile it to work on aarch64 (for raspberry pi)

it might seem stupid but i am interested in this project and i need some help.

**Comment by klange** [comment]
> `sudo docker run`

You should not run docker with `sudo`. You should add your user to the appropriate group to run `docker` as yourself. If you run docker as root, the permissions on files produced within the container may cause issues.

**Comment by klange** [comment]
Did you make an attempt to build that failed? The last step in the `build-in-docker.sh` removes the `util/local` symlink. You can try removing it manually before proceeding - the scripts were not intended for active development.

**Comment by TunifyBasic** [comment]
thank that was helpful.
