### ISSUE TITLE
Cannot booting in EFI mode for Virtualbox and Actual Machine

### ISSUE THREAD

**Issue by archanaberry** [klange/toaruos#302]
Please fix bootloader for efi combine BIOS Boot and EFI boot

**Comment by klange** [comment]
I am unable to provide support for running ToaruOS on real hardware.

As for VirtualBox, I was able to boot both the last published release build as well as the current CI build with EFI in VirtualBox 7.0.16 (the latest release available from apt in Ubuntu 24.04 LTS), but please do note that VirtualBox does not officially support booting _any_ OS with its EFI mode beyond the ones its setup wizard configures as such.
