### ISSUE TITLE
mmu_page_is_user_writable doesn't check if page is user accessible

### ISSUE THREAD

**Issue by MyEyes** [klange/toaruos#303]
`mmu_page_is_user_writable` only checks if the page is writable, not if it should be accessible to the user.

This has immediate impact in `ptrace_poke`, since that only sanitizes `data` but not `addr` allowing for arbitrary write anywhere in the kernel, since those pages still exist and are writable.

**Comment by klange** [comment]
Amusingly, I do the right thing in the aarch64 port: https://github.com/klange/toaruos/blob/master/base/usr/include/kernel/arch/aarch64/pml.h#L39

I suspect the mistake in the x86-64 code stems from forgetting that while the R/W flag normally only affects userspace, with the implementation of modest CoW support for x86-64 the WP bit has been set and kernel pages have also been marked as writable: https://github.com/klange/toaruos/blob/master/kernel/arch/x86_64/mmu.c#L945
