### ISSUE TITLE
TCP connection closing

### ISSUE THREAD

**Issue by klange** [klange/toaruos#51]

**Comment by omefire** [comment]
Could you please provide a description ?

**Comment by klange** [comment]
Of what? TCP connection closing? There's a diagram [on Wikipedia](http://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Tcp_state_diagram_fixed_new.svg/1084px-Tcp_state_diagram_fixed_new.svg.png).

**Comment by omefire** [comment]
I don't understand. is this an issue ? or is this a feature request.
I plan on contributing and thought this might be a good issue to pick up.

**Comment by klange** [comment]
This is part of a large set of TODOs for implementing TCP/IP.

**Comment by klange** [comment]
Github, unfortunately, lacks any concept of "issue types"...

**Comment by omefire** [comment]
Ooh I see,
