### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by cycl0ne** [klange/toaruos#55]
Hi,
i booted up the system with qemu 2.0 yesterday and the mouse wont work anymore. Not sure if it is the qemu 2.x (also installed 2.1 to verify). But since you are only doing "ps2" port things, it should work. Will try to set up a qemu 1.x to verify if there is something "new" in qemu.

**Comment by klange** [comment]
I actually haven't been able to reproduce this issue in a long time, so I think it was fixed in qemu or on our end at some point. *shrug*
