### ISSUE TITLE
x86-64 Port

### ISSUE THREAD

**Issue by klange** [klange/toaruos#58]
ToaruOS has been x86 32-bit only for quite some time. A half-hearted attempt at an ARM port was made in 2013, but was not completed. Porting to x86-64 would provide an opportunity to discover and fix size issues, built out the general port infrastructure that Toaru's build tools have been lacking, and also provide an environment where all of the general-purpose drivers (mouse/keyboard/video) continue to function.

Things to think about:
- Where are we making bad assumptions about pointer sizes?
- What can we do to make the build scripts support multiple target architectures?
- How can we make process structures more generic?
- Where do we make assumptions about memory layout that may no longer be true as we move to higher-half with x86-64?

**Comment by gil0mendes** [comment]
For the build system we could use some thing like jam or scons, personally I like more of scons. Make is slow, old and it is hard to make something more complex.

**Comment by klange** [comment]
I have no interest in actually replacing the build system; the required work to support ports in the existing makefile is minimal.

**Comment by io12** [comment]
To make ports to other architectures easier, there should be a clear separation between hardware dependent and hardware independent code. NetBSD does this.

**Comment by Je06jm** [comment]
I'm new to the project, but I am going to working on the x86_64 port. For right now, I'm just going to be working on the kernel. It's going to allow the operating system to run in a legacy 32 bit mode while the kernel runs in 64 bit mode. This will allow the operating system to be transitioned bit by bit.

**Comment by klange** [comment]
As rebuilding the userspace is a fairly simple matter (and it should be mostly architecture independent, beyond some bits of the crt libs), it may be worthwhile to try to take the opposite approach, like OS X did during its 64-bit transition, and set up the kernel so it can run a 64-bit userspace while the kernel mode remains 32-bit.

**Comment by Je06jm** [comment]
That's probably not a bad idea...

**Comment by Je06jm** [comment]
Is there any documentation anywhere? I'm finding myself digging through tons of code in order to understand the flow of the kernel.

**Comment by Je06jm** [comment]
I've decided to rebuild large parts of the kernel so that it will more portable and will support SMP. Software compatibility will be kept as much as possible.

**Comment by maxdev1** [comment]
> rebuild large parts of the kernel

Quite adventurous.

**Comment by Je06jm** [comment]
I believe that it's necessary. As it is written now, it will not scale or port very well. It is also written without SMP in mind and it's most likely to be unsafe for SMP. Most of the pointers are also explicitly set to 32 bits instead of a generic pointer type. I believe that a rewrite is the only way to achieve some of the long term goals for this project.

**Comment by Je06jm** [comment]
Since I'm going to do a rewrite, I'm going to make it easier for other people to contribute to it. The rewrite will also allow for the opportunity to add new features. What features do you want to see implemented?
