### ISSUE TITLE
glogin improvements

### ISSUE THREAD

**Issue by klange** [klange/toaruos#63]
There are several things that could use improvement in glogin:
- [x] Text input boxes need cursor when highlighted (preferably with blink)
- [x] Entire interface needs mouse support
- [x] The clock in the corner doesn't update (it's only a date, so this is pretty minor, but if you're logging in around midnight you might notice)
- [x] Yutani doesn't focus the login window when it is the only window (after logging out)
- [x] Add additional controls to login screen, such as "shut down"
- [x] Make design things configurable (transparency, layout, logo, etc.)

**Comment by makerimages** [comment]
add

- [ ] Looks ugly

to that list
