### ISSUE TITLE
Build a better sub-second timing API

### ISSUE THREAD

**Issue by klange** [klange/toaruos#65]
Currently, the only way to get accurate sub-second timing information is through the uptime interface, which is disturbingly wrong (though slightly interesting from a plan9 perspective...)

There are several places where sub-second timing information would be useful:
- Ensuring smooth animations in the compositor.
- Support double clicks properly.
- Video playback.

One of the POSIX timing APIs should be fully implemented with at least millisecond accuracy, but preferably microsecond accuracy (which is currently lacking). May require general upgrades to timekeeping.

**Comment by sortie** [comment]
Note gettimeofday is obsolete. The modern (and superior) interface is `clock_gettime`, which supports multiple clocks in nanosecond precision (which should prove sufficient for everything, struct timespec is the standard super timestamp format having replaced struct timeval). Monotonic time is nice for games and other applications where elapsed time is more important than clock time, which might not be continuous.

**Comment by klange** [comment]
The internal clock is now used for `gettimeofday`. The resolution has been increased to milliseconds. In the future, I'd like to add more precision with the TSC or another such clock source, but this is a good middle ground for the interim.

**Comment by gerow** [comment]
> I'd like to add more precision with the TSC or another such clock source
This Issue is ancient, so has that happened yet? If not it sounds neat and I might try to make it happen. Either way I guess I'll be poking through the code today so I'll probably know before you read this.

**Comment by klange** [comment]
The tough thing about actually use the TSC usefully is that it needs calibration since it's linked to clock speed rather than wallclock. Perhaps, moving forward, TSC would be useful as the timing source for wallclock information and we can keep using the PIT as the main preemption source... A lot of the problems with this ticket were fixed by increasing the PIT rate.
