### ISSUE TITLE
Initial kernel stack location

### ISSUE THREAD

**Issue by sortie** [klange/toaruos#73]
The kernel entry point:
```asm
global start
start:
	; Set up stack pointer.
	mov esp, 0x7FFFF
```
Sets up the kernel's initial stack at 0x7FFFF, which is a safe location according to the x86 memory layout. However, the kernel uses multiboot and also uses the multiboot information structure. The multiboot standard however explicitly states the bootloader is allowed to load it anywhere and it is the responsibility of the kernel not to corrupt it. There is a risk of conflict here.

The kernel entry point should instead allocate a sufficiently sized and aligned (16-byte per i386 ABI) stack in the bss and set that at start. This way the bootloader knows about the stack's location and there's no risk of collision.

**Comment by sortie** [comment]
Worse, I just realized 0x7FFFF is just 1-byte aligned! You meant 0x80000!

**Comment by graphitemaster** [comment]
This is fixed now.
