### ISSUE TITLE
Unsafe CMOS RFC reading

### ISSUE THREAD

**Issue by sortie** [klange/toaruos#76]
The realtime clock is read in an unsafe manner. The osdev wiki article is very worried that you might capture a moment where the clock is still updating. The kernel currently only reads a single snapshot and assumes it's good. It would be better to use the strategy from the wiki where it is read twice and compared, if different, it keeps reading. This should be essentially as fast and safe.

Additionally gettimeofday only keeps track of whole seconds. It would be better if the RTC was read on boot and then the timer interrupt will add to the current cached time. This way the get-time system call can return a higher precision value.

**Comment by klange** [comment]
See also #65 which discusses deficiencies in timing APIs.
