### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by klange** [klange/toaruos#78]
Getting some basic functionality for symlinks isn't difficult. Some of the POSIX semantics are a bit more complicated, though. Either way, we should get some symlink support in, as it's both important for some larger software packages, is blocking a good implementation of #77, and is just generally all-around useful.

I'm actually surprised I didn't already have a ticket for this...

**Comment by hambone69** [comment]
Stop sendin emails plaese. And what phone is this nokia 521 no more. Took
44mag shot it.  Junk ass phone
