### ISSUE TITLE
Make login look nice.

### ISSUE THREAD

**Issue by makerimages** [klange/toaruos#81]
The IRC examples looked great!

    <klange> Makerimages: Also, I assert that the login screen looks naked without a background box        for the inputs: http://i.imgur.com/XHlQjZ6.png
    <klange> Perhaps you would like the 50% transparent box rather than the 75% transparent box: http://i.imgur.com/x0mJouI.png

**Comment by klange** [comment]
DUPE #63 !

**Comment by makerimages** [comment]
Oh right... SO that's where I saw that....
