### ISSUE TITLE
Common symbols (COM) in modules are not allocated properly

### ISSUE THREAD

**Issue by gerow** [klange/toaruos#87]
I was poking around and noticed that an uninitialized static in a module I was using wasn't properly being zeroed. I've produced an example in a branch of mine called bss-issue: https://github.com/gerow/toaruos/tree/bss-issue

Curiously, the .bss section in bss_test.ko seems to be of Size 0:

```
$ readelf -S hdd/mod/bss_test.ko 
There are 15 section headers, starting at offset 0x204:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        00000000 000040 000058 00  AX  0   0 16
  [ 2] .rel.text         REL             00000000 00061c 000028 08     13   1  4
  [ 3] .data             PROGBITS        00000000 000098 000018 00  WA  0   0  4
  [ 4] .rel.data         REL             00000000 000644 000030 08     13   3  4
  [ 5] .bss              NOBITS          00000000 0000b0 000000 00  WA  0   0  4
  [ 6] .rodata.str1.1    PROGBITS        00000000 0000b0 000018 01 AMS  0   0  1
  [ 7] moddeps           PROGBITS        00000000 0000c8 00000b 00  WA  0   0  1
  [ 8] .rodata.str1.4    PROGBITS        00000000 0000d4 000031 01 AMS  0   0  4
  [ 9] .comment          PROGBITS        00000000 000105 000012 01  MS  0   0  1
  [10] .eh_frame         PROGBITS        00000000 000118 000078 00   A  0   0  4
  [11] .rel.eh_frame     REL             00000000 000674 000018 08     13  10  4
  [12] .shstrtab         STRTAB          00000000 000190 000071 00      0   0  1
  [13] .symtab           SYMTAB          00000000 00045c 000130 10     14  15  4
  [14] .strtab           STRTAB          00000000 00058c 00008f 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)
```

Is the .bss section supposed to have a size, or is there some magic going on that I'm unaware of? Either way, the fact that sometimes these statics are nonzero is a bit troubling.

**Comment by klange** [comment]
hey, what do ya know, we've actually got a TODO for this: https://github.com/klange/toaruos/blob/strawberry-dev/kernel/sys/module.c#L61

**Comment by gerow** [comment]
Huh, I remembered seeing that but assumed that TODO was left in on accident since this part of the module code appears to be attempting to load NOBITS types properly:
https://github.com/klange/toaruos/blob/strawberry-dev/kernel/sys/module.c#L130-L132

**Comment by klange** [comment]
I bet that malloc probably needs to be page aligned...

**Comment by gerow** [comment]
Perhaps. I added a debug line to print the size of that section, though, and for my test it seems to be allocating zero memory, which lines up with what readelf is showing above:

```
[0000000000.063:kernel/main.c:178] NOTICE: Loading a module: 0x00186000:0x0018668c
[0000000000.063:kernel/sys/module.c:131] ERROR: Loading NOBITS sized 0
[0000000000.064:kernel/sys/module.c:171] NOTICE: point bss_value to 0x00186001
[0000000000.064:kernel/sys/module.c:262] NOTICE: Finished loading module bss_test
[0000000000.065:kernel/main.c:181] NOTICE: Loaded: bss_test
```

It almost seems like it's getting linked improperly. That or the compiler is doing something wonky and putting it in another section.

**Comment by klange** [comment]
Ah, this isn't a BSS issue, it's a linking issue.

I did this:
```c
static uint8_t bss_value_a;
uint8_t bss_value_b;
uint8_t bss_value_c = 0;
```

```
bss_value_a: 0, 0x002a308d
bss_value_b: 69, 0x0017f001
bss_value_c: 0, 0x002a308c
```

`bss_value_b` isn't even in the BSS, I'm pretty sure it's ending up in `.text`.

**Comment by klange** [comment]
`18: 00000001     1 OBJECT  GLOBAL DEFAULT  COM bss_value_b`

Yeah, we're not loading `COM` indexes correctly.

**Comment by klange** [comment]
And here is where the incorrect behavior is happening: https://github.com/klange/toaruos/blob/strawberry-dev/kernel/sys/module.c#L167-L174

We realize we have a "common" symbol that we haven't set in our internal symbol table yet, so we point it towards... the beginning of the loaded module, without zeroing it.

There are two situations where we can find these common symbols in a module:
- A symbol from the kernel that was mistakenly not marked `extern` in a header. These work out because we check for presence of the symbol in the table before assigning it. See: Several places where we look at kernel version information.
- A symbol that was not initialized within the module. Like this. This is definitely wrong, these should at least be zero'd, and ideally should point somewhere better.

The workaround is to always initialize your 0'd stuff to 0, or mark it static. The solution would be to fix these symbol loads.

**Comment by klange** [comment]
Right, that index is actually the size of the symbol for these kinds of symbols, so we can put them wherever we want (maybe allocate some common space as we need it). The other option is to reject undefined common symbols, and require explicit zeroing... It's 1:30 AM for me so I'm going to call that it for investigating this.

**Comment by gerow** [comment]
Sounds good. The workaround is easy enough and the problem seems to be limited just to kernel modules, so this isn't a huge deal. I'll probably see if I can put together a fix eventually.

**Comment by klange** [comment]
I think the right approach for handling common symbols would be to just calloc some space for them. We don't have the same situation as a typical linker, which would examine all of the objects to try to find a definition before giving up and zeroing - we have a very strict hierarchy of symbol resolution, so if we see an as-yet undefined common symbol, we immediately know we can zero it and allocate space. I should also go in and fix the handful of kernel symbols that aren't marked extern in headers, to eliminate as many false-positive common symbols as we can.

**Comment by gerow** [comment]
Thanks!
