### ISSUE TITLE
System Updater

### ISSUE THREAD

**Issue by vincenzofehring** [klange/toaruos#97]
A system Updater should be implemented to provide users a solid and simple way to update their system to the newest version.

**Comment by DemHydraz** [comment]
I think this needs networking first.

**Comment by DemHydraz** [comment]
This would need an userspace interface to the in-kernel networking.
(@klange right?)

**Comment by gerow** [comment]
This could probably done through a proper packaging system. Networking would certainly make it nicer but it wouldn't be necessary.

**Comment by makerimages** [comment]
#105

**Comment by vincenzofehring** [comment]
I am still learning how to develop such low level systems, so I am not able to implement this. How is this feature looking at being integrated? This would be a great way to help the system become self sustaining.

**Comment by klange** [comment]
With the introduction of a functioning package manager that extracts packages to the filesystem, this is essentially done. There's still work to do with the filesystem drivers to provide enough stability for changes to a harddisk installation to persist between boots (allowing for packages for newer kernels).
